#!/bin/bash

if [ "$1" == "rec2pdbqt" ]
then
    CMD=$GALILEOHOME/src/galileo.rec2pdbqt.sh

elif [ "$1" == "box" ]
then
    CMD=$GALILEOHOME/src/galileo.box.sh

elif [ "$1" == "vina" ]
then
    CMD=$GALILEOHOME/src/galileo.ctrl.vina.sh

elif [ "$1" == "prepare_ad4" ]
then
    CMD=$GALILEOHOME/src/galileo.prepare_ad4.sh

elif [ "$1" == "ad4" ]
then
    CMD=$GALILEOHOME/src/galileo.ctrl.ad4.sh
fi



shift 
eval $CMD $@

